### PR TITLE
Move everything into toplevel site

### PR DESCRIPTION
**Pull request by diptorupd**
We do not need the scipy-poster sub directory any more. Removed the old poster directory as well.

### CODE REVIEW

**Comment by oleksandr-pavlyk** [comment]
@diptorupd Why so many new files added? Most of them are Node modules, it appears.

**Comment by oleksandr-pavlyk** [comment]
I think the overwriting of `README.md` from specific one we had to the one from Docsy example is a mistake.

**Comment by diptorupd** [comment]
> I think the overwriting of `README.md` from specific one we had to the one from Docsy example is a mistake.

FIXED that.

**Comment by diptorupd** [comment]
> @diptorupd Why so many new files added? Most of them are Node modules, it appears.

Yes, let me see.

**Comment by diptorupd** [comment]
@oleksandr-pavlyk check it now

**Comment by oleksandr-pavlyk** [comment]
Overall it looks good, but I am not entirely sure we need `CONTRIBUTING.md` and `docker-compose.yaml`.

**Review by oleksandr-pavlyk — APPROVED** [review]

**Pull request merged**
